### ISSUE TITLE
workflow: !important

### ISSUE THREAD

**Issue by moocunsw** [moocunsw/ontask2_UNSW#13]
if the primary column is set to type txt, the second step says
"Error
The 'type' of the primary column is incorrectly configured"

if we have zids, these are actually strings, not numbers

**Comment by stevenphaedonos** [comment]
I believe this is now resolved. Please update your datasource (i.e. re-upload the csv) and setting 'text' type in the primary field should not result in any errors. You'll need to clear cache because some changes were made front-end too.
